name: QA

on:
  pull_request:
  push:
  workflow_call:

env:
  # renovate: datasource=docker depName=node versioning=node
  NODE_VERSION: "20.18.0"

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
